spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://hselfweb.cn:3306/mes?serverTimezone=CTT
    username: mes
    password: Zncwhmz4fsLweYAt
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  address:
  port: 8080
